[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
